#pragma config(Motor,  port1,           RSL,           tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           drive_right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           drive_left,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           cube_roller,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Declare the RSL port as motor port 1
Declare the right drive train motor as port 2
Declare the left drive train motor as port 3
Declare the intake motor as port 9

When the program runs:
Turn on the RSL flashlight.

Loop the following while 1 is equal to 1:
Set the speed of the motor equal to the input of the inverted left stick vertical axis plus the left stick horizontal axis multiplied by a sensitivity & culling value.
Set the speed of the motor equal to the input of the inverted left stick vertical axis minus the left stick horizontal axis multiplied by a sensitivity & culling value.

If the button 8D is pressed, run the cube roller motor at maximum speed.
If the button 8D is not pressed, stop the cube roller motor.
*/

task main() //-----------------------------------------------------------------------------
{
	turnFlashlightOn(RSL); //turn on the RSL as a signal the robot code is running
	while(1==1)
	{
		motor[drive_left]=(vexRT[Ch3] * -0.9) + (vexRT[Ch4] * 0.5); //set the motor value of the left drive motor equal to the value of the vertical axis (multiplied by a culling value) plus the horitzontal axis (multiplied by a culling value)
		motor[drive_right]=(vexRT[Ch3] * -0.9) - (vexRT[Ch4] * 0.5); //set the motor value of the left drive motor equal to the value of the vertical axis (multiplied by a culling value) minus the horitzontal axis (multiplied by a culling value)
		//turning sens used to be 0.9
		if (vexRT[Btn8D] == 1){
			startMotor(cube_roller, -127); //start the roller if the button is being pressed
		}
		else
		{
			stopMotor(cube_roller); //stop the roller if the button is not being pressed
		}
	}
}
