#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    line,           sensorLineFollower)
#pragma config(Sensor, in3,    light,          sensorReflection)
#pragma config(Sensor, dgtl1,  ultrasonicIn,   sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl6,  LimitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int speed = 1;
task main() {

	SensorValue(encoder) = 0;
	while(SensorValue(encoder)<=80)
	{

		speed = 120 - SensorValue(encoder);
		startMotor(rightMotor, speed);
		waitInMilliseconds(250);
		stopMotor(rightMotor);
	}

}
