#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    line,           sensorLineFollower)
#pragma config(Sensor, in3,    light,          sensorReflection)
#pragma config(Sensor, dgtl1,  ultrasonicIn,   sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ultrasonicOut,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int speed = 0;
task main()
{
	speed = 0;
	SensorValue(encoder) = 0;
	while(SensorValue(encoder)!=720)
	{
		if ((SensorValue(encoder)<0))
		{
		speed = 1;
		}

		if ((SensorValue(encoder)<240))
		{
		speed = 2;
		}
		if ((SensorValue(encoder)<360))
		{
		speed = 3;
		}
		if ((SensorValue(encoder)>=360))
		{
		speed = 4;
		}

		switch(speed)
		{
			case 1:
			{
				startMotor(leftMotor, 120);
				break;
			}
			case 2:
			{
				stopMotor(leftMotor);
				startMotor(leftMotor, 60);
				break;
			}
			case 3:
			{
				stopMotor(leftMotor);
				startMotor(leftMotor, 20);
				break;
			}
			case 4:
			{
				stopMotor(leftMotor);
				startMotor(leftMotor, 0);
				break;
			}
		}
	}
	stopMotor(leftMotor);
}
