#pragma config(Motor,  port9,           test,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startMotor(test, 127);


}
